name: Auto Filter Nikki Nodes

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:


jobs:
  filter:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install dependency
      run: |
        pip install pyyaml


    - name: Download subscription
      run: |
        mkdir -p input

        curl -L \
        "https://github.com/Au1rxx/free-vpn-subscriptions/raw/main/output/clash.yaml" \
        -o input/all.yaml


    - name: Run filter
      run: |
        python filter_nodes.py


    - name: Commit result
      run: |

        git config user.name github-actions

        git config user.email github-actions@github.com

        git add output

        git commit -m "auto update filtered nodes" || exit 0

        git push