name: Nikki Auto Speed Filter

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:


jobs:

  filter:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"


    - name: Install Python packages
      run: |
        pip install pyyaml requests


    - name: Download subscription
      run: |
        mkdir -p input

        curl -L \
        "https://github.com/Au1rxx/free-vpn-subscriptions/raw/main/output/clash.yaml" \
        -o input/all.yaml


    - name: Download mihomo
      run: |

        wget -O mihomo.gz \
        https://github.com/MetaCubeX/mihomo/releases/download/v1.19.31/mihomo-linux-amd64-v1.19.31.gz

        gunzip mihomo.gz

        chmod +x mihomo

        sudo mv mihomo /usr/local/bin/mihomo


    - name: Run filter
      run: |
        python filter_nodes.py
    - name: Run mihomo speed test
      run: |
        chmod +x /usr/local/bin/mihomo
        mihomo -v

        python speed_test.py


    - name: Commit result
      run: |

        git config user.name github-actions

        git config user.email github-actions@github.com

        git add output

        git commit -m "auto update nikki nodes" || exit 0

        git push
